spring.application.name=alanwilliams-platform
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

alanwilliams.security.clerk.issuer=${CLERK_ISSUER}
alanwilliams.security.clerk.authorized-parties=${CLERK_AUTHORIZED_PARTIES}
clerk.secret-key=${CLERK_SECRET_KEY}

server.servlet.context-path=/platform